name: CI
on:
  pull_request:
  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    name: unit tests
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8
          coverage: xdebug

      - name: Install composer dependencies
        uses: ./.github/actions/install-composer-dependencies
        with:
          with-dev: yes

      - name: Run unit tests
        run: composer test-unit
  linting:
    runs-on: ubuntu-latest
    name: linting
    steps:
      - uses: actions/checkout@v3

      - name: Install composer dependencies
        uses: ./.github/actions/install-composer-dependencies
        with:
          with-dev: yes

      - name: Run code sniffer
        run: composer test-cs

